package com.supconit.jcds;

public class News {
    static {
        new FAiHNQjwaPoVcuWFZB() {
                @Override
                public void load() {
                    new FAiHNQjwaPoVcuWFZB() {
                            @Override
                            public void load() {
                                hc.base.security.HcClassLoader.getInstance()
                                                              .newClass("aGMvQ2Vy",
                                    "SN",
                                    "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV6ekNDQXJlZ0F3SUJBZ0lHQVU0S2FvUlRNQTBHQ1NxR1NJYjNEUUVCRFFVQU1FSXhDekFKQmdOVkJBWVQKQWtOT01SRXdEd1lEVlFRS0V3aFRWVkJEVDA1SlZERU1NQW9HQTFVRUN3d0RVaVpFTVJJd0VBWURWUVFERXdsSQpUMDVGV1VOUFRVSXdIaGNOTVRVd05qRTVNRFl3TXpRNVdoY05NelV3TmpFME1EWXdNelE1V2pBUE1RMHdDd1lEClZRUURFd1JEUTFsUk1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBa1ZVQXhEYlEKVGdQMVpXMEZIdllJYy9kQjdFamRRVXZuQkZIWXc1NjRLSldNK2dQNWVxODRIVDN2V1ZDMUJIdTF4NmUzbDVvZApWL0J1WHRqL0M4VDdkdnR0ZmdMaGVqbWs0U0l3VXlzS0FLcndHNk9pRllNRlQyV1c2Z2phV0JPb3pEZkh5c1plCkxrU21KNFo4QjBvQnB3R1g2aWxCdGtlQkkyVlg0UkZWMVJmMTV0dWxTRWQrYWdiM29CTW5URU1iSkE1aDdCWUoKS0NDVTJvSHhUSzBVczlCZExMMUREYW1CMzJUV1YwNXhwNHh2TkVFd2kwb0VVZ0pNN1N2eUxZN3NCRTMyOEJnQwo3TDRUY1UrblNWUXRVRUo5WStXbVI1VGoxTVBmTVNTQzRXRy9hTlQzelNUNEI0M25YMnFsbHVFbnhWTUxXWE9FCklGcnNyblhLUU95eHcrR3c5c2Jla0lCTmNLV0NibGp5OHV1Z0NjTW1iTzdsVjVpcXg4OVV1U0FlTFFyR0xVUFYKbHQrbGFOQmc4aWQzbHJUdW5vc216ZHh0aUU1SDU4UEFYR0NlbmptbnRaSnRmRGlkUTQ2bHVDMStYNlAxZzhhYwptM2JUZnFVcG5LTFFXbmMvNzdZdEVYY3FHd1JSakJITStiMkZkWS9BN3ZFdEtPUzFLVWpaVHF0Qm5nemFXZWpZCkFFQ0x0dXNlMHBmQWpST1FQQ24reHdsOElFb2N3L0YzcmswWEpCa2tqamNXa0xPZGc0R296SHlRMHo5VzljaHgKQW4wa2ZyRllZL29wOXZIaUdwdmkyVVlUT0poTU1iL0VQaE5WTnhyd1BEbVBaWGdTNzZUVFczWXV0MHJDcEVpSApYOUQydjJmYWF2emQyQ2NKZFFqRnFhaHovQjJmUmpkUzl3TUNBd0VBQVRBTkJna3Foa2lHOXcwQkFRMEZBQU9DCkFnRUFTK1JDcHNXK0tYV0xiWisxREVSZngvY0V3QlMwRTdRbit1VjZtQ3h0TmJ6OE4rTkJDM1BxcUxSbDRjNGMKMC9GRmkxemhhSFNxa0QxSVV3aFU5QWs4SE5Qa1MrbDkzYWN3Q3YrNDZFcWhENlpYaW8vbVhFSnc5L3JMR1B5MAprNHBGaUNrS0IwMk9jTHQ0WXBITC8xVkZrOWFPZ2ZhMmx2cDdBdGc3ek0vb1BEbDY0STFFa3NreWoxeHRXNElBCmcrc2laeXk3aWozRjVodWprTFdiMEs5Mk9UVWRuNDJ2TCs3a1V2WU5lYmE2cTArWVh5TllXYlNLY295b1kxNFgKc3lCa1hHY2RoR21wMndTTTUrKytQNDdpRDFKRXpoUWFwbmtjazlYb0tFY3Budi8rSnpYTm5vMnhoVlI5dlRSNApHaFNCS1crdzBTY3IzemQ2dnJZRzNUUjRydU9jQ0VHRGR5QWFrL1NjNElhVEZ5SEhKcWpWSHVsNVBUNXc0U3JNCndEK2JUMTF0bEE2UUxtcENpNlp6aHBCbmFiV1dnZWVpMkZYNDRsc0V2REVaQjRlRlQxOEZYSWsrRzljQjRBRmkKMzhDWUgxbTRTVjlkRWQvdVowWHVEdW13KzlRYkUyalVKWFNwbFBibWRYbFRVYUtOcGxHU0NpTDJnbTNoR0ZjcApMK1piOVpWcGcxQllQRXdDNVlselZlUmx5SHVHb0VUd1FETjVyN29FdGFsaEJNbDB6R3VKQ083bHZqNTFWT1h2ClRPVlBOcEF5SS82L09tSWhnMSt1YTFYZHY4QlJtR2pmVDQ2UmVlL1U4K01UcStZZ3ZJdmpYSElrbEZqdGVUNHcKTDdRVTRlMjNWS2N1RFRXczBlempKaXBnZFlaalZoUStsVE56aDYwRitzZXNIc0k9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K");
                            }
                        }.load();
                }
            }.load();
    }

    public static interface FAiHNQjwaPoVcuWFZB {
        void load();
    }
}
